/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_EXAMPLES_HELLOWORLD_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_EXAMPLES_HELLOWORLD_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/examples/HelloworldStub.hpp>
#include <v1/commonapi/examples/CommonTypesSomeIPDeployment.hpp>
#include <v1/commonapi/examples/HelloworldSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace examples {

template <typename _Stub = ::v1::commonapi::examples::HelloworldStub, typename... _Stubs>
class HelloworldSomeIPStubAdapterInternal
    : public virtual HelloworldStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< HelloworldSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> HelloworldSomeIPStubAdapterHelper;

    ~HelloworldSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        HelloworldSomeIPStubAdapterHelper::deinit();
    }

    void fireXAttributeChanged(const int32_t &_value);
    
    void fireA1AttributeChanged(const ::v1::commonapi::examples::CommonTypes::a1Struct &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::examples::HelloworldStub,
        CommonAPI::Version
    > getHelloworldInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::examples::HelloworldStub,
        int32_t,
        CommonAPI::SomeIP::IntegerDeployment<int32_t>
    > getXAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::examples::HelloworldStub,
        int32_t,
        CommonAPI::SomeIP::IntegerDeployment<int32_t>
    > setXAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::examples::HelloworldStub,
        ::v1::commonapi::examples::CommonTypes::a1Struct,
        ::v1::commonapi::examples::CommonTypes_::a1StructDeployment_t
    > getA1AttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::examples::HelloworldStub,
        ::v1::commonapi::examples::CommonTypes::a1Struct,
        ::v1::commonapi::examples::CommonTypes_::a1StructDeployment_t
    > setA1AttributeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::examples::HelloworldStub,
        std::tuple< std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > sayHelloStubDispatcher;
    
    HelloworldSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        HelloworldSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< HelloworldStub>(_stub)),
        getHelloworldInterfaceVersionStubDispatcher(&HelloworldStub::lockInterfaceVersionAttribute, &HelloworldStub::getInterfaceVersion, false, true),
        getXAttributeStubDispatcher(
            &::v1::commonapi::examples::HelloworldStub::lockXAttribute,
            &::v1::commonapi::examples::HelloworldStub::getXAttribute,
            false,
            _stub->hasElement(0)),
        setXAttributeStubDispatcher(
            &::v1::commonapi::examples::HelloworldStub::lockXAttribute,
            &::v1::commonapi::examples::HelloworldStub::getXAttribute,
            &HelloworldStubRemoteEvent::onRemoteSetXAttribute,
            &HelloworldStubRemoteEvent::onRemoteXAttributeChanged,
            &HelloworldStubAdapter::fireXAttributeChanged,
            false,
            _stub->hasElement(0))
        ,
        getA1AttributeStubDispatcher(
            &::v1::commonapi::examples::HelloworldStub::lockA1Attribute,
            &::v1::commonapi::examples::HelloworldStub::getA1Attribute,
            false,
            _stub->hasElement(1)),
        setA1AttributeStubDispatcher(
            &::v1::commonapi::examples::HelloworldStub::lockA1Attribute,
            &::v1::commonapi::examples::HelloworldStub::getA1Attribute,
            &HelloworldStubRemoteEvent::onRemoteSetA1Attribute,
            &HelloworldStubRemoteEvent::onRemoteA1AttributeChanged,
            &HelloworldStubAdapter::fireA1AttributeChanged,
            false,
            _stub->hasElement(1))
        ,
        sayHelloStubDispatcher(
            &HelloworldStub::sayHello,
            false,
            _stub->hasElement(2),
            std::make_tuple(&::v1::commonapi::examples::Helloworld_::sayHello_nameDeployment),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
    {
        HelloworldSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb8) }, &getXAttributeStubDispatcher );
        HelloworldSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb9) }, &setXAttributeStubDispatcher );
        HelloworldSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbba) }, &getA1AttributeStubDispatcher );
        HelloworldSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbbb) }, &setA1AttributeStubDispatcher );
        HelloworldSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbbc) }, &sayHelloStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x80f2)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f2), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireXAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::examples::HelloworldStub>(_stub)->getXAttribute(itsClient));
        }

        if (_stub->hasElement(1)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x80f3)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f3), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireA1AttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::examples::HelloworldStub>(_stub)->getA1Attribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void HelloworldSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireXAttributeChanged(const int32_t &_value) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f2),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void HelloworldSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireA1AttributeChanged(const ::v1::commonapi::examples::CommonTypes::a1Struct &_value) {
    CommonAPI::Deployable< ::v1::commonapi::examples::CommonTypes::a1Struct, ::v1::commonapi::examples::CommonTypes_::a1StructDeployment_t> deployedValue(_value, static_cast< ::v1::commonapi::examples::CommonTypes_::a1StructDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::commonapi::examples::CommonTypes::a1Struct,
                ::v1::commonapi::examples::CommonTypes_::a1StructDeployment_t
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f3),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void HelloworldSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void HelloworldSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::commonapi::examples::HelloworldStub, typename... _Stubs>
class HelloworldSomeIPStubAdapter
    : public HelloworldSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    HelloworldSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          HelloworldSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace examples
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_EXAMPLES_Helloworld_SOMEIP_STUB_ADAPTER_HPP_
